services:
  movie:
    build:
      context: .
      dockerfile: movie-service/src/Dockerfile
    image: ghcr.io/mazenaly256/csrs-movie

  reservation:
    build:
      context: .
      dockerfile: reservation-service/src/Dockerfile
    image: ghcr.io/mazenaly256/csrs-reservation

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway-service/src/Dockerfile
    image: ghcr.io/mazenaly256/csrs-api-gateway

  identity:
    build:
      context: .
      dockerfile: identity-service/src/Dockerfile
    image: ghcr.io/mazenaly256/csrs-identity
