networks:
  cinema-reservation-system-network:
    driver: bridge

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
    networks:
      - cinema-reservation-system-network

  movie-service:
    build:
      context: .
      dockerfile: movie-service/src/Dockerfile

    # Removed the ports section, hence the service can not be accessed directly from the host machine

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Server=sqlserver;Database=MovieServiceDB;User Id=sa;Password=Password123!;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - cinema-reservation-system-network
    deploy:
      resources:
        limits:
          cpus: "0.5" # Limit to half a core
          memory: 256M

  reservation-service:
    build:
      context: .
      dockerfile: reservation-service/src/Dockerfile

    # Removed the ports section, hence the service can not be accessed directly from the host machine

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - movieServiceBaseUrl=http://movie-service:8080
      - ConnectionStrings__Default=Server=sqlserver;Database=ReservationServiceDB;User Id=sa;Password=Password123!;TrustServerCertificate=True;
    depends_on:
      - sqlserver
      - movie-service
    networks:
      - cinema-reservation-system-network
    deploy:
      resources:
        limits:
          cpus: "0.5" # Limit to half a core
          memory: 256M

  api-gateway-service:
    build:
      context: .
      dockerfile: api-gateway-service/src/Dockerfile
    ports:
      - 5241:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ReverseProxy__Routes__movies-route__ClusterId=movie-service-containers
      - ReverseProxy__Routes__movies-route__Match__Path=/api/movies/{**catch-all}
      - ReverseProxy__Routes__showtimes-route__ClusterId=movie-service-containers
      - ReverseProxy__Routes__showtimes-route__Match__Path=/api/showtimes/{**catch-all}
      - ReverseProxy__Routes__reservations-route__ClusterId=reservation-service-containers
      - ReverseProxy__Routes__reservations-route__Match__Path=/api/reservations/{**catch-all}
      - ReverseProxy__Routes__seats-route__ClusterId=reservation-service-containers
      - ReverseProxy__Routes__seats-route__Match__Path=/api/seats/{**catch-all}
      - ReverseProxy__Clusters__movie-service-containers__Destinations__destination1__Address=http://movie-service:8080
      - ReverseProxy__Clusters__reservation-service-containers__Destinations__destination1__Address=http://reservation-service:8080
    depends_on:
      - sqlserver
      - movie-service
      - reservation-service
    networks:
      - cinema-reservation-system-network
    deploy:
      resources:
        limits:
          cpus: "0.5" # Limit to half a core
          memory: 256M
