// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using reservation_service.Data;

#nullable disable

namespace reservation_service.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("reservation_service.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("reservation_service.Models.Reservation", b =>
                {
                    b.Property<Guid>("ShowtimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShowtimeId", "SeatNumber");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("Reservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_SeatNumber_Format", "SeatNumber LIKE '[A-D][1-4]'");
                        });
                });

            modelBuilder.Entity("reservation_service.Models.SeatHold", b =>
                {
                    b.Property<Guid>("ShowtimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("HeldUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("ShowtimeId", "SeatNumber");

                    b.ToTable("SeatHolds", null, t =>
                        {
                            t.HasCheckConstraint("CK_SeatNumber_Format", "SeatNumber LIKE '[A-D][1-4]'")
                                .HasName("CK_SeatNumber_Format1");
                        });
                });

            modelBuilder.Entity("reservation_service.Models.Reservation", b =>
                {
                    b.HasOne("reservation_service.Models.Payment", "Payment")
                        .WithOne("Reservation")
                        .HasForeignKey("reservation_service.Models.Reservation", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("reservation_service.Models.Payment", b =>
                {
                    b.Navigation("Reservation");
                });
#pragma warning restore 612, 618
        }
    }
}
