// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using movie_service.Data;

#nullable disable

namespace movie_service.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260411072350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("movie_service.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Name = "Drama"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Name = "Crime"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("movie_service.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            DurationMinutes = 180,
                            Name = "Oppenheimer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            DurationMinutes = 166,
                            Name = "Dune: Part Two"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            DurationMinutes = 148,
                            Name = "Spider-Man: No Way Home"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            DurationMinutes = 176,
                            Name = "The Batman"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            DurationMinutes = 169,
                            Name = "Interstellar"
                        });
                });

            modelBuilder.Entity("movie_service.Models.MovieGenre", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres", (string)null);

                    b.HasData(
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000001"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000001"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000002"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000002"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000003"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000003"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000004"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000004"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000005"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000005"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("movie_service.Models.Showtime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Showtimes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            EndTime = new DateTime(2026, 4, 11, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000001"),
                            StartTime = new DateTime(2026, 4, 11, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            EndTime = new DateTime(2026, 4, 11, 23, 36, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000002"),
                            StartTime = new DateTime(2026, 4, 11, 21, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            EndTime = new DateTime(2026, 4, 12, 18, 28, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000003"),
                            StartTime = new DateTime(2026, 4, 12, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            EndTime = new DateTime(2026, 4, 12, 21, 56, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000004"),
                            StartTime = new DateTime(2026, 4, 12, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            EndTime = new DateTime(2026, 4, 13, 22, 49, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000005"),
                            StartTime = new DateTime(2026, 4, 13, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            EndTime = new DateTime(2026, 4, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000001"),
                            StartTime = new DateTime(2026, 4, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            EndTime = new DateTime(2026, 4, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000001"),
                            StartTime = new DateTime(2026, 4, 12, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            EndTime = new DateTime(2026, 4, 13, 16, 36, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000002"),
                            StartTime = new DateTime(2026, 4, 13, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            EndTime = new DateTime(2026, 4, 11, 17, 28, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000003"),
                            StartTime = new DateTime(2026, 4, 11, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            EndTime = new DateTime(2026, 4, 13, 13, 49, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000005"),
                            StartTime = new DateTime(2026, 4, 13, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("movie_service.Models.MovieGenre", b =>
                {
                    b.HasOne("movie_service.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_service.Models.Movie", "Movie")
                        .WithMany("Genres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("movie_service.Models.Showtime", b =>
                {
                    b.HasOne("movie_service.Models.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("movie_service.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("movie_service.Models.Movie", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("Showtimes");
                });
#pragma warning restore 612, 618
        }
    }
}
