// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using movie_service.Data;

#nullable disable

namespace movie_service.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260524075231_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("movie_service.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Name = "Drama"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Name = "Crime"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("movie_service.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            DurationMinutes = 180,
                            Name = "Oppenheimer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            DurationMinutes = 166,
                            Name = "Dune: Part Two"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            DurationMinutes = 148,
                            Name = "Spider-Man: No Way Home"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            DurationMinutes = 176,
                            Name = "The Batman"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            DurationMinutes = 169,
                            Name = "Interstellar"
                        });
                });

            modelBuilder.Entity("movie_service.Models.MovieGenre", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres", (string)null);

                    b.HasData(
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000001"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000001"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000002"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000002"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000003"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000003"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000004"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000004"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000005"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            MovieId = new Guid("10000000-0000-0000-0000-000000000005"),
                            GenreId = new Guid("20000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("movie_service.Models.Showtime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Showtimes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            EndTime = new DateTime(2027, 4, 11, 19, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Price = 30m,
                            StartTime = new DateTime(2027, 4, 11, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            EndTime = new DateTime(2027, 4, 11, 21, 36, 0, 0, DateTimeKind.Utc),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Price = 35m,
                            StartTime = new DateTime(2027, 4, 11, 19, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            EndTime = new DateTime(2027, 4, 12, 16, 28, 0, 0, DateTimeKind.Utc),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Price = 25m,
                            StartTime = new DateTime(2027, 4, 12, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            EndTime = new DateTime(2027, 4, 12, 19, 56, 0, 0, DateTimeKind.Utc),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Price = 45m,
                            StartTime = new DateTime(2027, 4, 12, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            EndTime = new DateTime(2026, 12, 13, 20, 49, 0, 0, DateTimeKind.Utc),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Price = 35m,
                            StartTime = new DateTime(2026, 12, 13, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            EndTime = new DateTime(2026, 5, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Price = 40m,
                            StartTime = new DateTime(2026, 5, 11, 7, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            EndTime = new DateTime(2027, 1, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Price = 40m,
                            StartTime = new DateTime(2027, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            EndTime = new DateTime(2027, 1, 13, 14, 36, 0, 0, DateTimeKind.Utc),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Price = 50m,
                            StartTime = new DateTime(2027, 1, 13, 12, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            EndTime = new DateTime(2026, 5, 11, 15, 28, 0, 0, DateTimeKind.Utc),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Price = 45m,
                            StartTime = new DateTime(2026, 5, 11, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            EndTime = new DateTime(2026, 12, 11, 15, 28, 0, 0, DateTimeKind.Utc),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Price = 45m,
                            StartTime = new DateTime(2026, 12, 11, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000011"),
                            EndTime = new DateTime(2027, 12, 31, 11, 50, 0, 0, DateTimeKind.Utc),
                            MovieId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Price = 35m,
                            StartTime = new DateTime(2027, 12, 31, 7, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("movie_service.Models.MovieGenre", b =>
                {
                    b.HasOne("movie_service.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_service.Models.Movie", "Movie")
                        .WithMany("Genres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("movie_service.Models.Showtime", b =>
                {
                    b.HasOne("movie_service.Models.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("movie_service.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("movie_service.Models.Movie", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("Showtimes");
                });
#pragma warning restore 612, 618
        }
    }
}
