# For more info on HTTP files go to https://aka.ms/vs/httpfile

#Generate JWT for Admin
POST http://localhost:5089/api/auth/login
content-type: application/json
{
  "email":"admin1@csrs.com",
  "password":"123456"
}
###


#Generate JWT for Client
POST http://localhost:5089/api/auth/login
content-type: application/json
{
  "email":"client1@csrs.com",
  "password":"123456"
}
###